a = int(input("1"))
b = int(input("9"))

print("a =", a)
print("b =", b)
print("a + b =", a+b)
print("a - b =", a-b)
print("a * b =", a*b)
print("a ** b =", a**b)
print("a // b =", a//b)
print("a % b =", a%b)
